name: Refresh drone-violations data

on:
  workflow_dispatch:            # manual trigger
  schedule:
    - cron: '0 3 * * 1'         # every Monday 03:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python (you can pin a specific minor if preferred)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install deps & run the scraper
      - name: Run scraper
        run: |
          python -m pip install --quiet requests beautifulsoup4
          python scripts/update_violations.py

      # Commit only if the JSON changed
      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet data/violations.json; then
            echo "No changes."
          else
            git config user.name  "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add data/violations.json
            git commit -m "auto: refresh violations data"
            git push
          fi
